feat: add wenku8 parsing rule, with encoding bugs
JeffersonQin/lightnovel_epub pull request #2
Opened 2022-01-12 04:07 UTC by HYDlink

2022-01-12 07:32 UTC, JeffersonQin requested changes
大的逻辑还没看，到时候给我几个测试链接我跑一下，没问题就 merge 吧

2022-01-12 07:32 UTC, JeffersonQin commented on provider/wenku8.py
> +def getBookStructure(content: str) -> dict[str, list[BookInfo]]:
要 python 3.9 才支持 collection 的 typing

文件最上面加上 `from __future__ import annotations`

2022-01-12 07:32 UTC, JeffersonQin commented on provider/wenku8.py
> +import js2py
这个 import 可以删掉

2022-01-12 07:32 UTC, JeffersonQin commented on provider/wenku8.py
> +			content = downloader.download_webpage(url, DOCUMENT_DOWNLOAD_HEADERS)
定位到问题了，问题在 `downloader.download_webpage` 里，要用 `content` 进行 `gbk` 的 `decode`

等下我改一下 `downloader` 的代码然后你传一个 `encoding` 进去，应该就没问题了

2022-01-12 08:12 UTC, JeffersonQin commented on provider/wenku8.py
> +			content = downloader.download_webpage(url, DOCUMENT_DOWNLOAD_HEADERS)
这里没问题了，merge好以后你重新pull一下就好了

2022-01-12 08:39 UTC, JeffersonQin commented on provider/wenku8.py
> +					chWeb = downloader.download_webpage(addr, DOCUMENT_DOWNLOAD_HEADERS)
这里也是，加上 `encoding`

2022-01-12 08:40 UTC, JeffersonQin requested changes
两个 download_webpage 都是

2022-01-12 11:23 UTC, JeffersonQin commented on provider/wenku8.py
> +	content = soup.find('div', id='contentmain').text
这个要获取整个 html

2022-01-12 11:24 UTC, JeffersonQin commented on provider/wenku8.py
> +	res = downloader.download_webpage(url, DOCUMENT_DOWNLOAD_HEADERS)
download 前检查 cache

2022-01-20 11:44 UTC, HYDlink commented on provider/wenku8.py
> +	content = soup.find('div', id='contentmain').text
使用了 prettify()，可能使用 str() 强转即可

2022-01-20 11:45 UTC, HYDlink commented on provider/wenku8.py
> +	res = downloader.download_webpage(url, DOCUMENT_DOWNLOAD_HEADERS)
这个后续在 downloader 里面加吧

2022-01-20 13:12 UTC, JeffersonQin requested changes
删掉多余的import就行

2022-01-20 13:12 UTC, JeffersonQin commented on provider/wenku8.py
> +from genericpath import exists
这个好像没有必要欸

2022-01-20 14:13 UTC, JeffersonQin approved these changes
LGTM

2022-01-20 14:14 UTC, merged